# Generated by Django 6.0.5 on 2026-06-05 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('reason', models.TextField(verbose_name='Raison de la délégation')),
                ('permissions', models.JSONField(default=list, help_text='Liste des permissions (approve, reject, reassign, etc.)', verbose_name='Permissions déléguées')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_given', to=settings.AUTH_USER_MODEL, verbose_name='Délégant')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_received', to=settings.AUTH_USER_MODEL, verbose_name='Délégataire')),
            ],
            options={
                'verbose_name': 'Délégation',
                'verbose_name_plural': 'Délégations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Escalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('DELAY', 'Délai dépassé'), ('COMPLEXITY', 'Complexité du dossier'), ('CONFLICT', "Conflit d'intérêt"), ('MANUAL', 'Escalade manuelle'), ('OTHER', 'Autre')], max_length=20, verbose_name='Raison')),
                ('description', models.TextField(verbose_name='Description')),
                ('escalated_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'escalade")),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de résolution')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Résolu')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='complaints.complaint', verbose_name='Plainte')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations_sent', to=settings.AUTH_USER_MODEL, verbose_name='De')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations_received', to=settings.AUTH_USER_MODEL, verbose_name='Vers')),
            ],
            options={
                'verbose_name': 'Escalade',
                'verbose_name_plural': 'Escalades',
                'ordering': ['-escalated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReassignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Raison de la réaffectation')),
                ('reassigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de réaffectation')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reassignments', to='complaints.complaint', verbose_name='Plainte')),
                ('from_inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reassignments_from', to=settings.AUTH_USER_MODEL, verbose_name='Ancien inspecteur')),
                ('reassigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reassignments_done', to=settings.AUTH_USER_MODEL, verbose_name='Réaffecté par')),
                ('to_inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reassignments_to', to=settings.AUTH_USER_MODEL, verbose_name='Nouvel inspecteur')),
            ],
            options={
                'verbose_name': 'Réaffectation',
                'verbose_name_plural': 'Réaffectations',
                'ordering': ['-reassigned_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('INSPECTOR', 'Inspecteur'), ('CHIEF', "Chef d'Inspection"), ('REGIONAL', 'Directeur Régional'), ('NATIONAL', 'Directeur Général')], max_length=20, verbose_name='Niveau hiérarchique')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('comment', models.TextField(blank=True, verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'approbation")),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals_given', to=settings.AUTH_USER_MODEL, verbose_name='Approbateur')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='complaints.complaint', verbose_name='Plainte')),
            ],
            options={
                'verbose_name': 'Approbation',
                'verbose_name_plural': 'Approbations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['complaint', 'status'], name='hierarchy_w_complai_4c27f6_idx'), models.Index(fields=['approver', 'status'], name='hierarchy_w_approve_3f2853_idx')],
            },
        ),
    ]
