# Generated by Django 5.0.6 on 2026-06-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('EMPLOYE', 'Employé'), ('EMPLOYE_MAISON', 'Employé de Maison'), ('EMPLOYEUR', 'Employeur'), ('INSPECTEUR', 'Inspecteur'), ('CHEF_INSPECTION', "Chef d'Inspection"), ('DIRECTEUR_REGIONAL', 'Directeur Régional'), ('DIRECTEUR_GENERAL', 'Directeur Général'), ('ADMIN', 'Administrateur')], max_length=20, verbose_name="Type d'utilisateur"),
        ),
    ]
