# Generated by Django 6.0.5 on 2026-06-05 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('module', models.CharField(blank=True, max_length=100, verbose_name='Module')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'ordering': ['module', 'code'],
            },
        ),
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_type', models.CharField(choices=[('FULL', 'Complète'), ('INCREMENTAL', 'Incrémentale'), ('DATABASE', 'Base de données'), ('FILES', 'Fichiers')], max_length=20, verbose_name='Type')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('RUNNING', 'En cours'), ('COMPLETED', 'Terminée'), ('FAILED', 'Échouée')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='Chemin fichier')),
                ('file_size_mb', models.FloatField(default=0, verbose_name='Taille (MB)')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Démarré à')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé à')),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Lancé par')),
            ],
            options={
                'verbose_name': 'Log de sauvegarde',
                'verbose_name_plural': 'Logs de sauvegarde',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Actif')),
                ('message', models.TextField(default='Système en maintenance. Retour imminent.', verbose_name='Message')),
                ('scheduled_start', models.DateTimeField(blank=True, null=True, verbose_name='Début programmé')),
                ('scheduled_end', models.DateTimeField(blank=True, null=True, verbose_name='Fin programmée')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='Activé à')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Désactivé à')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_maintenance', to=settings.AUTH_USER_MODEL, verbose_name='Activé par')),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deactivated_maintenance', to=settings.AUTH_USER_MODEL, verbose_name='Désactivé par')),
            ],
            options={
                'verbose_name': 'Mode maintenance',
                'verbose_name_plural': 'Modes maintenance',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nom')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_system', models.BooleanField(default=False, verbose_name='Rôle système')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permissions', models.ManyToManyField(blank=True, to='administration.permission', verbose_name='Permissions')),
            ],
            options={
                'verbose_name': 'Rôle',
                'verbose_name_plural': 'Rôles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True, verbose_name='Clé')),
                ('value', models.TextField(verbose_name='Valeur')),
                ('config_type', models.CharField(choices=[('GENERAL', 'Général'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('PAYMENT', 'Paiement'), ('SECURITY', 'Sécurité'), ('CUSTOM', 'Personnalisé')], default='CUSTOM', max_length=20, verbose_name='Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_encrypted', models.BooleanField(default=False, verbose_name='Cryptée')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Configuration système',
                'verbose_name_plural': 'Configurations système',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('VIEW', 'Consultation'), ('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('EXPORT', 'Export'), ('IMPORT', 'Import')], max_length=20, verbose_name='Action')),
                ('model_name', models.CharField(max_length=100, verbose_name='Modèle')),
                ('object_id', models.IntegerField(blank=True, null=True, verbose_name='ID objet')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='Représentation')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Changements')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Log d'audit",
                'verbose_name_plural': "Logs d'audit",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'action'], name='administrat_user_id_aba423_idx'), models.Index(fields=['model_name', 'object_id'], name='administrat_model_n_ad7686_idx'), models.Index(fields=['created_at'], name='administrat_created_befdf2_idx')],
            },
        ),
    ]
