# Generated by Django 6.0.5 on 2026-06-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('DIRECTEUR_GENERAL', 'Directeur Général'), ('DIRECTEUR_REGIONAL', 'Directeur Régional'), ('CHEF_INSPECTION', "Chef d'Inspection"), ('INSPECTEUR', 'Inspecteur du Travail'), ('EMPLOYEUR', 'Employeur'), ('EMPLOYE', 'Employé')], max_length=30, verbose_name='Rôle')),
                ('permission', models.CharField(max_length=100, verbose_name='Permission')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Droit par rôle',
                'verbose_name_plural': 'Droits par rôle',
                'ordering': ['role', 'permission'],
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
