# Generated by Django 6.0.5 on 2026-06-05 18:12

import django.db.models.deletion
import judicial.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JudicialProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_number', models.CharField(default=judicial.models.generate_procedure_number, max_length=50, unique=True, verbose_name='Numéro de procédure')),
                ('procedure_type', models.CharField(choices=[('LABOR_DISPUTE', 'Litige du travail'), ('WRONGFUL_TERMINATION', 'Licenciement abusif'), ('DISCRIMINATION', 'Discrimination'), ('HARASSMENT', 'Harcèlement'), ('UNPAID_WAGES', 'Salaires impayés'), ('WORKPLACE_ACCIDENT', 'Accident de travail'), ('OTHER', 'Autre')], max_length=30, verbose_name='Type de procédure')),
                ('status', models.CharField(choices=[('PREPARATION', 'En préparation'), ('SUBMITTED', 'Soumise au tribunal'), ('UNDER_REVIEW', 'En examen'), ('HEARING_SCHEDULED', 'Audience programmée'), ('AWAITING_DECISION', 'En délibéré'), ('DECIDED', 'Jugement rendu'), ('APPEAL', 'En appel'), ('CLOSED', 'Clôturée')], default='PREPARATION', max_length=20, verbose_name='Statut')),
                ('defendant_name', models.CharField(max_length=255, verbose_name='Défendeur')),
                ('defendant_representative', models.CharField(blank=True, max_length=255, verbose_name='Représentant du défendeur')),
                ('court_name', models.CharField(max_length=255, verbose_name='Tribunal')),
                ('court_reference', models.CharField(blank=True, max_length=100, verbose_name='Référence tribunal')),
                ('judge_name', models.CharField(blank=True, max_length=255, verbose_name='Juge')),
                ('filed_date', models.DateField(blank=True, null=True, verbose_name='Date de dépôt')),
                ('submission_date', models.DateField(blank=True, null=True, verbose_name='Date de transmission')),
                ('summary', models.TextField(verbose_name="Résumé de l'affaire")),
                ('legal_grounds', models.TextField(blank=True, verbose_name='Fondements juridiques')),
                ('claims', models.TextField(verbose_name='Demandes')),
                ('claimed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Montant réclamé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='judicial_procedures_managed', to=settings.AUTH_USER_MODEL, verbose_name='Chargé du dossier')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judicial_procedures', to='complaints.complaint', verbose_name='Plainte')),
                ('plaintiff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedures_as_plaintiff', to=settings.AUTH_USER_MODEL, verbose_name='Plaignant')),
            ],
            options={
                'verbose_name': 'Procédure judiciaire',
                'verbose_name_plural': 'Procédures judiciaires',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JudicialDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_type', models.CharField(choices=[('JUDGMENT', 'Jugement'), ('ORDER', 'Ordonnance'), ('RULING', 'Arrêt'), ('SETTLEMENT', 'Transaction homologuée')], max_length=20, verbose_name='Type de décision')),
                ('outcome', models.CharField(choices=[('FAVOR_PLAINTIFF', 'En faveur du plaignant'), ('FAVOR_DEFENDANT', 'En faveur du défendeur'), ('PARTIAL', 'Partiellement favorable'), ('DISMISSED', 'Rejetée'), ('SETTLED', 'Transaction')], max_length=20, verbose_name='Issue')),
                ('decision_date', models.DateField(verbose_name='Date de la décision')),
                ('notification_date', models.DateField(blank=True, null=True, verbose_name='Date de notification')),
                ('summary', models.TextField(verbose_name='Résumé de la décision')),
                ('full_text', models.TextField(blank=True, verbose_name='Texte intégral')),
                ('awarded_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Montant accordé')),
                ('damages', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Dommages et intérêts')),
                ('legal_costs', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Frais de justice')),
                ('is_enforceable', models.BooleanField(default=True, verbose_name='Exécutoire')),
                ('is_final', models.BooleanField(default=False, verbose_name='Définitif')),
                ('appeal_deadline', models.DateField(blank=True, null=True, verbose_name="Délai d'appel")),
                ('decision_file', models.FileField(blank=True, null=True, upload_to='judicial/decisions/', verbose_name='Fichier de la décision')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('procedure', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='judicial.judicialprocedure', verbose_name='Procédure')),
            ],
            options={
                'verbose_name': 'Décision judiciaire',
                'verbose_name_plural': 'Décisions judiciaires',
                'ordering': ['-decision_date'],
            },
        ),
        migrations.CreateModel(
            name='Hearing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hearing_type', models.CharField(choices=[('PRELIMINARY', 'Audience préliminaire'), ('MAIN', 'Audience principale'), ('WITNESS', 'Audition de témoin'), ('EXPERT', 'Expertise'), ('DELIBERATION', 'Délibéré'), ('JUDGMENT', 'Prononcé du jugement')], max_length=20, verbose_name="Type d'audience")),
                ('status', models.CharField(choices=[('SCHEDULED', 'Programmée'), ('POSTPONED', 'Reportée'), ('COMPLETED', 'Tenue'), ('CANCELLED', 'Annulée')], default='SCHEDULED', max_length=20, verbose_name='Statut')),
                ('scheduled_date', models.DateTimeField(verbose_name='Date programmée')),
                ('actual_date', models.DateTimeField(blank=True, null=True, verbose_name='Date effective')),
                ('location', models.CharField(max_length=255, verbose_name='Lieu')),
                ('room', models.CharField(blank=True, max_length=100, verbose_name='Salle')),
                ('judge', models.CharField(blank=True, max_length=255, verbose_name='Juge')),
                ('plaintiff_present', models.BooleanField(default=False, verbose_name='Plaignant présent')),
                ('defendant_present', models.BooleanField(default=False, verbose_name='Défendeur présent')),
                ('minutes', models.TextField(blank=True, verbose_name='Compte-rendu')),
                ('next_steps', models.TextField(blank=True, verbose_name='Suites à donner')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearings', to='judicial.judicialprocedure', verbose_name='Procédure')),
            ],
            options={
                'verbose_name': 'Audience',
                'verbose_name_plural': 'Audiences',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='CourtDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('COMPLAINT_FORM', 'Formulaire de plainte'), ('EVIDENCE', 'Pièce à conviction'), ('WITNESS_STATEMENT', 'Témoignage'), ('EXPERT_REPORT', "Rapport d'expert"), ('LEGAL_BRIEF', 'Mémoire'), ('COURT_ORDER', 'Ordonnance'), ('SUMMONS', 'Assignation'), ('JUDGMENT', 'Jugement'), ('OTHER', 'Autre')], max_length=20, verbose_name='Type de document')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('file', models.FileField(upload_to='judicial/documents/', verbose_name='Fichier')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Uploadé par')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='judicial.judicialprocedure', verbose_name='Procédure')),
            ],
            options={
                'verbose_name': 'Document judiciaire',
                'verbose_name_plural': 'Documents judiciaires',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.AddIndex(
            model_name='judicialprocedure',
            index=models.Index(fields=['procedure_number'], name='judicial_ju_procedu_9f00e6_idx'),
        ),
        migrations.AddIndex(
            model_name='judicialprocedure',
            index=models.Index(fields=['status', 'filed_date'], name='judicial_ju_status_662713_idx'),
        ),
    ]
