# Generated by Django 5.0.6 on 2026-06-07 20:34

import django.db.models.deletion
import domestic.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(default=domestic.models.generate_voice_case_number, max_length=30, unique=True, verbose_name='Numéro de dossier')),
                ('audio_file', models.FileField(upload_to='voice_complaints/audio/', verbose_name='Message vocal')),
                ('duration_seconds', models.IntegerField(default=0, verbose_name='Durée (s)')),
                ('detected_language', models.CharField(blank=True, choices=[('DIOULA', 'Dioula'), ('BAOULE', 'Baoulé'), ('BETE', 'Bété'), ('SENOUFO', 'Sénoufo'), ('ANYIN', 'Anyin'), ('FRENCH', 'Français'), ('OTHER', 'Autre')], max_length=20, verbose_name='Langue détectée')),
                ('language_confidence', models.FloatField(default=0.0, verbose_name='Confiance (%)')),
                ('commune', models.CharField(blank=True, max_length=100, verbose_name='Commune')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('ASSIGNED', 'Assigné'), ('IN_PROGRESS', 'En cours'), ('RESPONDED', 'Répondu'), ('ASSISTANCE_REQUESTED', 'Assistance linguistique demandée'), ('CLOSED', 'Clôturé')], default='PENDING', max_length=30, verbose_name='Statut')),
                ('inspector_response_text', models.TextField(blank=True, verbose_name='Réponse texte')),
                ('inspector_response_audio', models.FileField(blank=True, null=True, upload_to='voice_complaints/responses/', verbose_name='Réponse audio')),
                ('language_assistance_requested', models.BooleanField(default=False, verbose_name='Assistance linguistique demandée')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_voice_complaints', to=settings.AUTH_USER_MODEL, verbose_name='Inspecteur assigné')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_complaints', to='domestic.domesticworker', verbose_name='Employée')),
            ],
            options={
                'verbose_name': 'Déclaration vocale',
                'verbose_name_plural': 'Déclarations vocales',
                'ordering': ['-created_at'],
            },
        ),
    ]
