# Generated by Django 5.0.6 on 2026-06-07 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic', '0002_add_voice_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Début heures sup')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Fin heures sup')),
                ('duration_minutes', models.IntegerField(default=0, verbose_name='Durée (minutes)')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Motif')),
                ('is_active', models.BooleanField(default=True, verbose_name='En cours')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_sessions', to='domestic.timetracking', verbose_name='Pointage du jour')),
            ],
            options={
                'verbose_name': 'Session heures supplémentaires',
                'verbose_name_plural': 'Sessions heures supplémentaires',
                'ordering': ['-start_time'],
            },
        ),
    ]
