# Generated by Django 6.0.5 on 2026-06-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic', '0003_add_overtime_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicecomplaint',
            name='selected_language',
            field=models.CharField(blank=True, choices=[('DIOULA', 'Dioula'), ('BAOULE', 'Baoulé'), ('BETE', 'Bété'), ('SENOUFO', 'Sénoufo'), ('ANYIN', 'Anyin'), ('FRENCH', 'Français'), ('OTHER', 'Autre')], max_length=20, verbose_name='Langue choisie'),
        ),
        migrations.AddField(
            model_name='voicecomplaint',
            name='transcription_french',
            field=models.TextField(blank=True, verbose_name='Traduction en français'),
        ),
        migrations.AddField(
            model_name='voicecomplaint',
            name='transcription_original',
            field=models.TextField(blank=True, verbose_name='Transcription (langue originale)'),
        ),
        migrations.AddField(
            model_name='voicecomplaint',
            name='transcription_status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('PROCESSING', 'En cours'), ('DONE', 'Terminée'), ('FAILED', 'Échouée')], default='PENDING', max_length=20, verbose_name='Statut transcription'),
        ),
    ]
