# Generated by Django 6.0.5 on 2026-06-05 17:32

import django.core.validators
import django_countries.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Nom de l'entreprise")),
                ('legal_form', models.CharField(choices=[('SARL', 'SARL'), ('SA', 'SA'), ('SAS', 'SAS'), ('EI', 'Entreprise Individuelle'), ('SASU', 'SASU'), ('SNC', 'SNC'), ('AUTRE', 'Autre')], max_length=50, verbose_name='Forme juridique')),
                ('rccm', models.CharField(max_length=100, unique=True, verbose_name='RCCM')),
                ('cc', models.CharField(blank=True, max_length=100, verbose_name='CC (Registre de Commerce)')),
                ('nif', models.CharField(max_length=100, unique=True, verbose_name='NIF')),
                ('cnps_number', models.CharField(blank=True, max_length=100, verbose_name='Numéro CNPS')),
                ('sector', models.CharField(choices=[('AGRICULTURE', 'Agriculture'), ('INDUSTRIE', 'Industrie'), ('COMMERCE', 'Commerce'), ('SERVICES', 'Services'), ('CONSTRUCTION', 'Construction'), ('TRANSPORT', 'Transport'), ('SANTE', 'Santé'), ('EDUCATION', 'Éducation'), ('FINANCE', 'Finance'), ('TECHNOLOGIE', 'Technologie'), ('HOTELLERIE', 'Hôtellerie et Restauration'), ('AUTRE', 'Autre')], max_length=50, verbose_name="Secteur d'activité")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('headquarters_address', models.TextField(verbose_name='Adresse du siège')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Région/Département')),
                ('country', django_countries.fields.CountryField(default='CG', max_length=2, verbose_name='Pays')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('employee_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Nombre d'employés")),
                ('founding_date', models.DateField(blank=True, null=True, verbose_name='Date de création')),
                ('compliance_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Score de conformité')),
                ('risk_level', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyen'), ('HIGH', 'Élevé'), ('CRITICAL', 'Critique')], default='LOW', max_length=20, verbose_name='Niveau de risque social')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Vérifiée')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnterpriseBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom de la succursale')),
                ('address', models.TextField(verbose_name='Adresse')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('manager_name', models.CharField(blank=True, max_length=200, verbose_name='Nom du responsable')),
                ('employee_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Nombre d'employés")),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Succursale',
                'verbose_name_plural': 'Succursales',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EnterpriseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('RCCM', 'RCCM'), ('NIF', 'NIF'), ('CNPS', 'Attestation CNPS'), ('STATUTS', 'Statuts'), ('LICENCE', "Licence d'exploitation"), ('AUTRE', 'Autre')], max_length=50, verbose_name='Type de document')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('file', models.FileField(upload_to='enterprises/documents/', verbose_name='Fichier')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name="Date d'émission")),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('is_verified', models.BooleanField(default=False, verbose_name='Vérifié')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Document d'entreprise",
                'verbose_name_plural': "Documents d'entreprise",
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='EnterpriseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CREATION', 'Création'), ('UPDATE', 'Mise à jour'), ('INSPECTION', 'Inspection'), ('COMPLAINT', 'Plainte'), ('SANCTION', 'Sanction'), ('PROCEDURE', 'Procédure judiciaire')], max_length=50, verbose_name="Type d'événement")),
                ('description', models.TextField(verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Historique d'entreprise",
                'verbose_name_plural': "Historiques d'entreprise",
                'ordering': ['-created_at'],
            },
        ),
    ]
