# Generated by Django 6.0.5 on 2026-06-05 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprises', '0001_initial'),
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='inspection_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprises', to='inspections.inspectionzone', verbose_name="Zone d'inspection"),
        ),
        migrations.AddField(
            model_name='enterprisebranch',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='enterprises.enterprise', verbose_name='Entreprise'),
        ),
        migrations.AddField(
            model_name='enterprisedocument',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='enterprises.enterprise', verbose_name='Entreprise'),
        ),
        migrations.AddField(
            model_name='enterprisehistory',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='enterprises.enterprise', verbose_name='Entreprise'),
        ),
    ]
