# Generated by Django 6.0.5 on 2026-06-05 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprises', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprisehistory',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Effectué par'),
        ),
        migrations.AddIndex(
            model_name='enterprise',
            index=models.Index(fields=['rccm'], name='enterprises_rccm_7a4565_idx'),
        ),
        migrations.AddIndex(
            model_name='enterprise',
            index=models.Index(fields=['nif'], name='enterprises_nif_e84caa_idx'),
        ),
        migrations.AddIndex(
            model_name='enterprise',
            index=models.Index(fields=['sector'], name='enterprises_sector_99c9d3_idx'),
        ),
        migrations.AddIndex(
            model_name='enterprise',
            index=models.Index(fields=['city'], name='enterprises_city_9381bc_idx'),
        ),
        migrations.AddIndex(
            model_name='enterprise',
            index=models.Index(fields=['compliance_score'], name='enterprises_complia_aa2167_idx'),
        ),
        migrations.AddIndex(
            model_name='enterprise',
            index=models.Index(fields=['risk_level'], name='enterprises_risk_le_ee7824_idx'),
        ),
    ]
