# Generated by Django 6.0.5 on 2026-06-05 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('calculation_method', models.TextField(verbose_name='Méthode de calcul')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Unité')),
                ('target_value', models.FloatField(blank=True, null=True, verbose_name='Valeur cible')),
                ('warning_threshold', models.FloatField(blank=True, null=True, verbose_name='Seuil alerte')),
                ('critical_threshold', models.FloatField(blank=True, null=True, verbose_name='Seuil critique')),
                ('current_value', models.FloatField(blank=True, null=True, verbose_name='Valeur actuelle')),
                ('last_calculated_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernier calcul')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Catégorie')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'KPI',
                'verbose_name_plural': 'KPIs',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('widgets', models.JSONField(default=list, verbose_name='Widgets')),
                ('layout', models.JSONField(default=dict, verbose_name='Layout')),
                ('is_public', models.BooleanField(default=False, verbose_name='Public')),
                ('allowed_roles', models.JSONField(blank=True, default=list, verbose_name='Rôles autorisés')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_dashboards', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DataExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('export_format', models.CharField(choices=[('CSV', 'CSV'), ('EXCEL', 'Excel'), ('PDF', 'PDF'), ('JSON', 'JSON')], max_length=20, verbose_name='Format')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PROCESSING', 'En cours'), ('COMPLETED', 'Terminé'), ('FAILED', 'Échoué')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('model_name', models.CharField(max_length=100, verbose_name='Modèle')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='Filtres')),
                ('columns', models.JSONField(blank=True, default=list, verbose_name='Colonnes')),
                ('file', models.FileField(blank=True, upload_to='exports/%Y/%m/', verbose_name='Fichier')),
                ('file_size_mb', models.FloatField(default=0, verbose_name='Taille (MB)')),
                ('rows_count', models.IntegerField(default=0, verbose_name='Nombre de lignes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé à')),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_exports', to=settings.AUTH_USER_MODEL, verbose_name='Demandé par')),
            ],
            options={
                'verbose_name': 'Export de données',
                'verbose_name_plural': 'Exports de données',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('report_type', models.CharField(choices=[('TABLE', 'Tableau'), ('CHART', 'Graphique'), ('PIVOT', 'Tableau croisé'), ('CUSTOM', 'Personnalisé')], max_length=20, verbose_name='Type')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PUBLISHED', 'Publié'), ('ARCHIVED', 'Archivé')], default='DRAFT', max_length=20, verbose_name='Statut')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('query', models.TextField(blank=True, verbose_name='Requête SQL')),
                ('query_params', models.JSONField(blank=True, default=dict, verbose_name='Paramètres requête')),
                ('chart_config', models.JSONField(blank=True, default=dict, verbose_name='Configuration graphique')),
                ('is_scheduled', models.BooleanField(default=False, verbose_name='Planifié')),
                ('schedule_cron', models.CharField(blank=True, max_length=100, verbose_name='Cron schedule')),
                ('cached_data', models.JSONField(blank=True, default=dict, verbose_name='Données en cache')),
                ('cache_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expiration cache')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reports', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'ordering': ['-created_at'],
            },
        ),
    ]
