# Generated by Django 6.0.5 on 2026-06-05 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mediation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateTimeField(verbose_name='Date de la séance')),
                ('session_type', models.CharField(choices=[('PRESENTIAL', 'Présentiel'), ('ONLINE', 'En ligne (visioconférence)'), ('HYBRID', 'Hybride')], max_length=20, verbose_name='Type de séance')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Programmée'), ('ONGOING', 'En cours'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée'), ('POSTPONED', 'Reportée')], default='SCHEDULED', max_length=20, verbose_name='Statut')),
                ('location', models.TextField(blank=True, verbose_name='Lieu')),
                ('meeting_link', models.URLField(blank=True, verbose_name='Lien de réunion')),
                ('outcome', models.CharField(choices=[('AGREEMENT', 'Accord trouvé'), ('PARTIAL_AGREEMENT', 'Accord partiel'), ('NO_AGREEMENT', 'Aucun accord'), ('PENDING', 'En attente')], default='PENDING', max_length=20, verbose_name='Résultat')),
                ('outcome_notes', models.TextField(blank=True, verbose_name='Notes sur le résultat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediations', to='complaints.complaint', verbose_name='Plainte')),
                ('mediator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mediations_conducted', to=settings.AUTH_USER_MODEL, verbose_name='Médiateur')),
            ],
            options={
                'verbose_name': 'Médiation',
                'verbose_name_plural': 'Médiations',
                'ordering': ['-session_date'],
            },
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_text', models.TextField(verbose_name="Texte de l'accord")),
                ('terms', models.JSONField(default=list, verbose_name="Termes de l'accord")),
                ('employee_obligations', models.TextField(blank=True, verbose_name="Obligations de l'employé")),
                ('employer_obligations', models.TextField(blank=True, verbose_name="Obligations de l'employeur")),
                ('compensation_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Montant de compensation')),
                ('execution_deadline', models.DateField(blank=True, null=True, verbose_name="Date limite d'exécution")),
                ('employee_signature', models.ImageField(blank=True, null=True, upload_to='mediations/agreements/signatures/', verbose_name='Signature employé')),
                ('employer_signature', models.ImageField(blank=True, null=True, upload_to='mediations/agreements/signatures/', verbose_name='Signature employeur')),
                ('mediator_signature', models.ImageField(blank=True, null=True, upload_to='mediations/agreements/signatures/', verbose_name='Signature médiateur')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PENDING_SIGNATURE', 'En attente de signature'), ('SIGNED', 'Signé'), ('EXECUTED', 'Exécuté'), ('BREACHED', 'Violé')], default='DRAFT', max_length=20, verbose_name='Statut')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de signature')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='mediations/agreements/', verbose_name='Accord (PDF)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mediation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agreement', to='mediations.mediation', verbose_name='Médiation')),
            ],
            options={
                'verbose_name': 'Accord de médiation',
                'verbose_name_plural': 'Accords de médiation',
            },
        ),
        migrations.CreateModel(
            name='MediationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('CONVOCATION', 'Convocation'), ('MINUTES', 'Procès-verbal'), ('AGREEMENT', 'Accord'), ('EVIDENCE', 'Pièce justificative'), ('CORRESPONDENCE', 'Correspondance'), ('OTHER', 'Autre')], max_length=20, verbose_name='Type de document')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('file', models.FileField(upload_to='mediations/documents/', verbose_name='Fichier')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('mediation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='mediations.mediation', verbose_name='Médiation')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Uploadé par')),
            ],
            options={
                'verbose_name': 'Document de médiation',
                'verbose_name_plural': 'Documents de médiation',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='MediationMinutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_statement', models.TextField(verbose_name="Déclaration d'ouverture")),
                ('employee_statement', models.TextField(blank=True, verbose_name='Déclaration employé')),
                ('employer_statement', models.TextField(blank=True, verbose_name='Déclaration employeur')),
                ('discussion_summary', models.TextField(verbose_name='Résumé des discussions')),
                ('agreements_reached', models.JSONField(default=list, verbose_name='Accords conclus')),
                ('signed_by_all', models.BooleanField(default=False, verbose_name='Signé par tous')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de signature')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='mediations/minutes/', verbose_name='PV (PDF)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mediation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='minutes', to='mediations.mediation', verbose_name='Médiation')),
            ],
            options={
                'verbose_name': 'Procès-verbal',
                'verbose_name_plural': 'Procès-verbaux',
            },
        ),
        migrations.CreateModel(
            name='MediationParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Nom')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('role', models.CharField(choices=[('EMPLOYEE', 'Employé'), ('EMPLOYER', 'Employeur'), ('WITNESS', 'Témoin'), ('LAWYER', 'Avocat'), ('REPRESENTATIVE', 'Représentant')], max_length=20, verbose_name='Rôle')),
                ('attended', models.BooleanField(default=False, verbose_name='A participé')),
                ('signed', models.BooleanField(default=False, verbose_name='A signé')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='mediations/signatures/', verbose_name='Signature')),
                ('convoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de convocation')),
                ('convocation_sent', models.BooleanField(default=False, verbose_name='Convocation envoyée')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mediation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='mediations.mediation', verbose_name='Médiation')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Participant')),
            ],
            options={
                'verbose_name': 'Participant médiation',
                'verbose_name_plural': 'Participants médiation',
            },
        ),
        migrations.AddIndex(
            model_name='mediation',
            index=models.Index(fields=['session_date', 'status'], name='mediations__session_d4ede2_idx'),
        ),
        migrations.AddIndex(
            model_name='mediation',
            index=models.Index(fields=['mediator', 'status'], name='mediations__mediato_e87183_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mediationparticipant',
            unique_together={('mediation', 'participant')},
        ),
    ]
