# Generated by Django 6.0.5 on 2026-06-05 17:32

import complaints.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_number', models.CharField(default=complaints.models.generate_complaint_number, max_length=50, unique=True, verbose_name='Numéro de plainte')),
                ('complaint_type', models.CharField(choices=[('UNPAID_SALARY', 'Salaire impayé'), ('TERMINATION', 'Licenciement abusif'), ('HARASSMENT', 'Harcèlement'), ('ACCIDENT', 'Accident de travail'), ('OVERTIME', 'Heures supplémentaires non payées'), ('LEAVE', 'Congés non respectés'), ('CONTRACT', 'Problème de contrat'), ('DISCRIMINATION', 'Discrimination'), ('WORKING_CONDITIONS', 'Conditions de travail'), ('OTHER', 'Autre')], max_length=50, verbose_name='Type de plainte')),
                ('subject', models.CharField(max_length=255, verbose_name='Objet')),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('employer_name', models.CharField(blank=True, max_length=255, verbose_name="Nom de l'employeur")),
                ('workplace_address', models.TextField(verbose_name='Adresse du lieu de travail')),
                ('workplace_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('workplace_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('incident_date', models.DateField(blank=True, null=True, verbose_name="Date de l'incident")),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('ASSIGNED', 'Assignée'), ('IN_PROGRESS', 'En cours de traitement'), ('UNDER_INVESTIGATION', 'En enquête'), ('MEDIATION', 'En médiation'), ('RESOLVED', 'Résolue'), ('CLOSED', 'Clôturée'), ('ESCALATED', 'Escaladée'), ('JUDICIAL', 'Procédure judiciaire')], default='PENDING', max_length=50, verbose_name='Statut')),
                ('priority', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Haute'), ('URGENT', 'Urgente')], default='MEDIUM', max_length=50, verbose_name='Priorité')),
                ('resolution', models.TextField(blank=True, verbose_name='Résolution')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de clôture')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Plainte',
                'verbose_name_plural': 'Plaintes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Commentaire')),
                ('is_internal', models.BooleanField(default=False, verbose_name='Interne (non visible au plaignant)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('CONTRACT', 'Contrat de travail'), ('PAYSLIP', 'Bulletin de paie'), ('PHOTO', 'Photo'), ('AUDIO', 'Audio'), ('VIDEO', 'Vidéo'), ('LETTER', 'Lettre/Courrier'), ('OTHER', 'Autre')], max_length=50, verbose_name='Type de document')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('file', models.FileField(upload_to='complaints/documents/', verbose_name='Fichier')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Document de plainte',
                'verbose_name_plural': 'Documents de plainte',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lu à')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=50, verbose_name='Ancien statut')),
                ('to_status', models.CharField(max_length=50, verbose_name='Nouveau statut')),
                ('reason', models.TextField(blank=True, verbose_name='Raison du changement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historique de statut',
                'verbose_name_plural': 'Historiques de statut',
                'ordering': ['created_at'],
            },
        ),
    ]
