# Generated by Django 6.0.5 on 2026-06-05 17:32

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom de la zone')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('region', models.CharField(max_length=100, verbose_name='Région')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Zone d'inspection",
                'verbose_name_plural': "Zones d'inspection",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InspectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_type', models.CharField(choices=[('ROUTINE', 'Routine'), ('FOLLOW_UP', 'Suivi'), ('COMPLAINT', 'Suite à plainte'), ('SPOT_CHECK', 'Contrôle inopiné')], max_length=50, verbose_name="Type d'inspection")),
                ('scheduled_date', models.DateTimeField(verbose_name='Date prévue')),
                ('actual_date', models.DateTimeField(blank=True, null=True, verbose_name='Date effective')),
                ('location', models.TextField(verbose_name='Lieu')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('findings', models.TextField(verbose_name='Constats')),
                ('recommendations', models.TextField(blank=True, verbose_name='Recommandations')),
                ('result', models.CharField(choices=[('COMPLIANT', 'Conforme'), ('MINOR_ISSUES', 'Non-conformités mineures'), ('MAJOR_ISSUES', 'Non-conformités majeures'), ('NON_COMPLIANT', 'Non conforme')], max_length=50, verbose_name='Résultat')),
                ('photos', models.JSONField(blank=True, default=list, verbose_name='Photos')),
                ('report_file', models.FileField(blank=True, null=True, upload_to='inspections/reports/', verbose_name='Rapport')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Terminée')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_records', to='enterprises.enterprise', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': "Enregistrement d'inspection",
                'verbose_name_plural': "Enregistrements d'inspection",
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
