# Generated by Django 6.0.5 on 2026-06-05 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0002_initial'),
        ('enterprises', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Nom de l'archive")),
                ('archive_type', models.CharField(choices=[('PHYSICAL', 'Physique'), ('DIGITAL', 'Numérique'), ('CLOUD', 'Cloud')], max_length=20, verbose_name='Type')),
                ('location', models.CharField(max_length=500, verbose_name='Emplacement')),
                ('capacity_gb', models.FloatField(blank=True, null=True, verbose_name='Capacité (GB)')),
                ('used_space_gb', models.FloatField(default=0, verbose_name='Espace utilisé (GB)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Archive',
                'verbose_name_plural': 'Archives',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nom')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('retention_years', models.IntegerField(default=5, verbose_name='Durée de rétention (années)')),
                ('is_archivable', models.BooleanField(default=True, verbose_name='Archivable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='ged.documentcategory', verbose_name='Catégorie parent')),
            ],
            options={
                'verbose_name': 'Catégorie de document',
                'verbose_name_plural': 'Catégories de documents',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('reference_number', models.CharField(max_length=100, unique=True, verbose_name='Numéro de référence')),
                ('file', models.FileField(upload_to='ged/documents/%Y/%m/', verbose_name='Fichier')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Taille (octets)')),
                ('file_type', models.CharField(blank=True, max_length=50, verbose_name='Type de fichier')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('ACTIVE', 'Actif'), ('ARCHIVED', 'Archivé'), ('DELETED', 'Supprimé')], default='ACTIVE', max_length=20, verbose_name='Statut')),
                ('is_confidential', models.BooleanField(default=False, verbose_name='Confidentiel')),
                ('access_level', models.IntegerField(default=1, verbose_name="Niveau d'accès (1-5)")),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Archivé le')),
                ('archive_location', models.CharField(blank=True, max_length=255, verbose_name='Emplacement archive')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_documents', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('related_complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ged_documents', to='complaints.complaint', verbose_name='Plainte liée')),
                ('related_enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ged_documents', to='enterprises.enterprise', verbose_name='Entreprise liée')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='ged.documentcategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(verbose_name='Numéro de version')),
                ('file', models.FileField(upload_to='ged/versions/%Y/%m/', verbose_name='Fichier')),
                ('change_description', models.TextField(blank=True, verbose_name='Description des changements')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='ged.document', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Version de document',
                'verbose_name_plural': 'Versions de documents',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('VIEW', 'Consultation'), ('DOWNLOAD', 'Téléchargement'), ('EDIT', 'Modification'), ('SHARE', 'Partage'), ('DELETE', 'Suppression')], max_length=20, verbose_name='Action')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='ged.document', verbose_name='Document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Accès document',
                'verbose_name_plural': 'Accès documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document', 'created_at'], name='ged_documen_documen_21ccbb_idx'), models.Index(fields=['user', 'action'], name='ged_documen_user_id_f44387_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['reference_number'], name='ged_documen_referen_4d1b4b_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status', 'category'], name='ged_documen_status_5ea2bf_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['created_at'], name='ged_documen_created_7f7561_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentversion',
            unique_together={('document', 'version_number')},
        ),
    ]
