# Generated by Django 6.0.5 on 2026-06-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Date')),
                ('complaints_total', models.IntegerField(default=0, verbose_name='Total plaintes')),
                ('complaints_new', models.IntegerField(default=0, verbose_name='Nouvelles plaintes')),
                ('complaints_resolved', models.IntegerField(default=0, verbose_name='Plaintes résolues')),
                ('complaints_pending', models.IntegerField(default=0, verbose_name='Plaintes en cours')),
                ('inspections_total', models.IntegerField(default=0, verbose_name='Total inspections')),
                ('inspections_completed', models.IntegerField(default=0, verbose_name='Inspections terminées')),
                ('enterprises_total', models.IntegerField(default=0, verbose_name='Total entreprises')),
                ('enterprises_at_risk', models.IntegerField(default=0, verbose_name='Entreprises à risque')),
                ('mediations_scheduled', models.IntegerField(default=0, verbose_name='Médiations programmées')),
                ('mediations_successful', models.IntegerField(default=0, verbose_name='Médiations réussies')),
                ('resolution_rate', models.FloatField(default=0, verbose_name='Taux de résolution (%)')),
                ('average_resolution_days', models.FloatField(default=0, verbose_name='Délai moyen résolution (jours)')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Statistiques quotidiennes',
                'verbose_name_plural': 'Statistiques quotidiennes',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(unique=True, verbose_name='Mois')),
                ('total_complaints', models.IntegerField(default=0)),
                ('total_inspections', models.IntegerField(default=0)),
                ('total_enterprises', models.IntegerField(default=0)),
                ('resolution_rate', models.FloatField(default=0)),
                ('compliance_rate', models.FloatField(default=0)),
                ('average_resolution_time', models.FloatField(default=0)),
                ('complaints_by_type', models.JSONField(default=dict)),
                ('complaints_by_region', models.JSONField(default=dict)),
                ('top_sectors_issues', models.JSONField(default=list)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rapport mensuel',
                'verbose_name_plural': 'Rapports mensuels',
                'ordering': ['-month'],
            },
        ),
    ]
