# Generated by Django 6.0.5 on 2026-06-05 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0002_initial'),
        ('enterprises', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbuseDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abuse_type', models.CharField(choices=[('HARASSMENT', 'Harcèlement'), ('DISCRIMINATION', 'Discrimination'), ('CHILD_LABOR', 'Travail des enfants'), ('FORCED_LABOR', 'Travail forcé'), ('UNSAFE_CONDITIONS', 'Conditions dangereuses'), ('WAGE_THEFT', 'Vol de salaire')], max_length=20, verbose_name="Type d'abus")),
                ('detection_score', models.FloatField(verbose_name='Score de détection (0-1)')),
                ('evidence_keywords', models.JSONField(default=list, verbose_name='Mots-clés détectés')),
                ('evidence_patterns', models.JSONField(default=list, verbose_name='Patterns détectés')),
                ('urgency_level', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyen'), ('HIGH', 'Élevé'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20, verbose_name="Niveau d'urgence")),
                ('recommended_actions', models.TextField(verbose_name='Actions recommandées')),
                ('authorities_notified', models.BooleanField(default=False, verbose_name='Autorités notifiées')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de notification')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abuse_detections', to='complaints.complaint', verbose_name='Plainte')),
            ],
            options={
                'verbose_name': "Détection d'abus",
                'verbose_name_plural': "Détections d'abus",
                'ordering': ['-detection_score', '-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True, verbose_name='ID de session')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de début')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('initial_topic', models.CharField(blank=True, max_length=255, verbose_name='Sujet initial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Conversation chatbot',
                'verbose_name_plural': 'Conversations chatbot',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('USER', 'Utilisateur'), ('ASSISTANT', 'Assistant IA'), ('SYSTEM', 'Système')], max_length=10, verbose_name='Rôle')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('tokens_used', models.IntegerField(default=0, verbose_name='Tokens utilisés')),
                ('model_used', models.CharField(blank=True, max_length=50, verbose_name='Modèle IA utilisé')),
                ('confidence_score', models.FloatField(blank=True, null=True, verbose_name='Score de confiance')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai.chatconversation', verbose_name='Conversation')),
            ],
            options={
                'verbose_name': 'Message chatbot',
                'verbose_name_plural': 'Messages chatbot',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_file', models.FileField(upload_to='ai/documents/', verbose_name='Document')),
                ('document_type', models.CharField(choices=[('CONTRACT', 'Contrat de travail'), ('PAYSLIP', 'Bulletin de paie'), ('TERMINATION', 'Lettre de licenciement'), ('COMPLAINT', 'Plainte écrite'), ('ID_CARD', "Carte d'identité"), ('OTHER', 'Autre')], default='OTHER', max_length=20, verbose_name='Type de document')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PROCESSING', 'En traitement'), ('COMPLETED', 'Terminé'), ('FAILED', 'Échoué')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('extracted_text', models.TextField(blank=True, verbose_name='Texte extrait (OCR)')),
                ('ocr_confidence', models.FloatField(blank=True, null=True, verbose_name='Confiance OCR')),
                ('ai_summary', models.TextField(blank=True, verbose_name='Résumé IA')),
                ('detected_issues', models.JSONField(blank=True, default=list, verbose_name='Problèmes détectés')),
                ('key_clauses', models.JSONField(blank=True, default=list, verbose_name='Clauses clés')),
                ('recommendations', models.TextField(blank=True, verbose_name='Recommandations')),
                ('language_detected', models.CharField(blank=True, max_length=10, verbose_name='Langue détectée')),
                ('processing_time_seconds', models.FloatField(blank=True, null=True, verbose_name='Temps de traitement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_analyses', to=settings.AUTH_USER_MODEL, verbose_name='Uploadé par')),
            ],
            options={
                'verbose_name': 'Analyse de document',
                'verbose_name_plural': 'Analyses de documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(verbose_name='Score de similarité (0-1)')),
                ('type_match', models.BooleanField(default=False, verbose_name='Type identique')),
                ('employer_match', models.BooleanField(default=False, verbose_name='Employeur identique')),
                ('text_similarity', models.FloatField(default=0, verbose_name='Similarité textuelle')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('complaint1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities_as_source', to='complaints.complaint', verbose_name='Plainte 1')),
                ('complaint2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities_as_target', to='complaints.complaint', verbose_name='Plainte 2')),
            ],
            options={
                'verbose_name': 'Similarité de plaintes',
                'verbose_name_plural': 'Similarités de plaintes',
                'ordering': ['-similarity_score'],
                'unique_together': {('complaint1', 'complaint2')},
            },
        ),
        migrations.CreateModel(
            name='RiskPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_type', models.CharField(choices=[('STRIKE', 'Grève'), ('MASS_LAYOFF', 'Licenciement collectif'), ('SOCIAL_UNREST', 'Conflit social'), ('ACCIDENT_RISK', "Risque d'accident"), ('LABOR_DISPUTE', 'Litige du travail')], max_length=20, verbose_name='Type de risque')),
                ('risk_level', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyen'), ('HIGH', 'Élevé'), ('CRITICAL', 'Critique')], max_length=20, verbose_name='Niveau de risque')),
                ('probability', models.FloatField(verbose_name='Probabilité (0-1)')),
                ('contributing_factors', models.JSONField(default=list, verbose_name='Facteurs contributifs')),
                ('preventive_actions', models.TextField(blank=True, verbose_name='Actions préventives')),
                ('model_version', models.CharField(blank=True, max_length=20, verbose_name='Version du modèle')),
                ('confidence_score', models.FloatField(blank=True, null=True, verbose_name='Confiance')),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_predictions', to='enterprises.enterprise', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Prédiction de risque',
                'verbose_name_plural': 'Prédictions de risques',
                'ordering': ['-predicted_at'],
                'indexes': [models.Index(fields=['enterprise', 'risk_level'], name='ai_riskpred_enterpr_ce0e25_idx')],
            },
        ),
    ]
