# Generated by Django 6.0.5 on 2026-06-05 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nom du template')),
                ('template_type', models.CharField(choices=[('COMPLAINT_CREATED', 'Plainte créée'), ('COMPLAINT_ASSIGNED', 'Plainte assignée'), ('STATUS_UPDATE', 'Mise à jour statut'), ('MEDIATION_INVITATION', 'Invitation médiation'), ('HEARING_NOTIFICATION', 'Notification audience'), ('DECISION_NOTIFICATION', 'Notification décision'), ('CONTRACT_SIGNED', 'Contrat signé'), ('PAYSLIP_GENERATED', 'Bulletin généré'), ('LEAVE_APPROVED', 'Congé approuvé'), ('CUSTOM', 'Personnalisé')], max_length=30, verbose_name='Type')),
                ('subject', models.CharField(max_length=255, verbose_name='Sujet')),
                ('html_content', models.TextField(verbose_name='Contenu HTML')),
                ('text_content', models.TextField(blank=True, verbose_name='Contenu texte')),
                ('available_variables', models.JSONField(blank=True, default=list, help_text='Ex: ["user_name", "complaint_number", "date"]', verbose_name='Variables disponibles')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template email',
                'verbose_name_plural': 'Templates email',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nom du template')),
                ('template_type', models.CharField(choices=[('COMPLAINT_CREATED', 'Plainte créée'), ('STATUS_UPDATE', 'Mise à jour'), ('APPOINTMENT_REMINDER', 'Rappel RDV'), ('VERIFICATION_CODE', 'Code vérification'), ('ALERT', 'Alerte'), ('CUSTOM', 'Personnalisé')], max_length=30, verbose_name='Type')),
                ('content', models.TextField(max_length=160, verbose_name='Contenu SMS (max 160 car)')),
                ('available_variables', models.JSONField(blank=True, default=list, verbose_name='Variables disponibles')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template SMS',
                'verbose_name_plural': 'Templates SMS',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('PUSH', 'Push')], max_length=10, verbose_name='Type')),
                ('recipient_id', models.IntegerField(verbose_name='ID destinataire')),
                ('recipient_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('recipient_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('template_name', models.CharField(max_length=255, verbose_name='Nom du template')),
                ('context_data', models.JSONField(default=dict, verbose_name='Données contextuelles')),
                ('priority', models.IntegerField(default=5, verbose_name='Priorité (1=haute, 10=basse)')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Programmé pour')),
                ('processed', models.BooleanField(default=False, verbose_name='Traité')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Traité le')),
                ('retry_count', models.IntegerField(default=0, verbose_name='Nombre de tentatives')),
                ('max_retries', models.IntegerField(default=3, verbose_name='Tentatives max')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'File notification',
                'verbose_name_plural': 'File notifications',
                'ordering': ['priority', 'created_at'],
                'indexes': [models.Index(fields=['processed', 'priority'], name='notificatio_process_ca3f0d_idx'), models.Index(fields=['scheduled_at'], name='notificatio_schedul_a6050c_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='Destinataire')),
                ('recipient_name', models.CharField(blank=True, max_length=255, verbose_name='Nom destinataire')),
                ('subject', models.CharField(max_length=255, verbose_name='Sujet')),
                ('body_html', models.TextField(verbose_name='Corps HTML')),
                ('body_text', models.TextField(blank=True, verbose_name='Corps texte')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SENT', 'Envoyé'), ('FAILED', 'Échoué'), ('BOUNCED', 'Rebond')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Envoyé le')),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('provider', models.CharField(blank=True, max_length=50, verbose_name='Fournisseur')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='Ouvert le')),
                ('clicked_at', models.DateTimeField(blank=True, null=True, verbose_name='Cliqué le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.emailtemplate', verbose_name='Template utilisé')),
            ],
            options={
                'verbose_name': 'Log email',
                'verbose_name_plural': 'Logs email',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient_email', 'status'], name='notificatio_recipie_d2c6d1_idx'), models.Index(fields=['created_at'], name='notificatio_created_eaa7a4_idx')],
            },
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_phone', models.CharField(max_length=20, verbose_name='Téléphone destinataire')),
                ('recipient_name', models.CharField(blank=True, max_length=255, verbose_name='Nom destinataire')),
                ('content', models.TextField(max_length=160, verbose_name='Contenu')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SENT', 'Envoyé'), ('DELIVERED', 'Délivré'), ('FAILED', 'Échoué')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Envoyé le')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Délivré le')),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('provider', models.CharField(blank=True, max_length=50, verbose_name='Fournisseur')),
                ('provider_message_id', models.CharField(blank=True, max_length=255, verbose_name='ID message fournisseur')),
                ('cost', models.DecimalField(decimal_places=4, default=0, max_digits=6, verbose_name='Coût')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.smstemplate', verbose_name='Template utilisé')),
            ],
            options={
                'verbose_name': 'Log SMS',
                'verbose_name_plural': 'Logs SMS',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient_phone', 'status'], name='notificatio_recipie_c50ca6_idx'), models.Index(fields=['created_at'], name='notificatio_created_1c846d_idx')],
            },
        ),
    ]
